
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 4
Maximale L„nge : 6

Startzeit: Thu Jan 24 08:46:34 1991
Endzeit:   Thu Jan 24 08:46:34 1991

Golomb Lineal :
0 1 4 6 

Zu messende Abst„nde :
  1   2   3   4   5   6 
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 5
Maximale L„nge : 11

Startzeit: Thu Jan 24 08:46:37 1991
Endzeit:   Thu Jan 24 08:46:37 1991

Golomb Lineal :
0 1 4 9 11 

Zu messende Abst„nde :
  1   2   3   4   5   7   8   9  10  11 

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 6
Maximale L„nge : 17

Startzeit: Thu Jan 24 08:46:40 1991
Endzeit:   Thu Jan 24 08:46:40 1991

Golomb Lineal :
0 1 4 10 12 17 

Zu messende Abst„nde :
  1   2   3   4   5   6   7   8   9  10 
 11  12  13  16  17 
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 7
Maximale L„nge : 25

Startzeit: Thu Jan 24 08:46:42 1991
Endzeit:   Thu Jan 24 08:46:42 1991

Golomb Lineal :
0 1 4 10 18 23 25 

Zu messende Abst„nde :
  1   2   3   4   5   6   7   8   9  10 
 13  14  15  17  18  19  21  22  23  24 
 25 
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 8
Maximale L„nge : 34

Startzeit: Thu Jan 24 08:46:45 1991
Endzeit:   Thu Jan 24 08:46:45 1991

Golomb Lineal :
0 1 4 9 15 22 32 34 

Zu messende Abst„nde :
  1   2   3   4   5   6   7   8   9  10 
 11  12  13  14  15  17  18  19  21  22 
 23  25  28  30  31  32  33  34 
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 9
Maximale L„nge : 44

Startzeit: Thu Jan 24 08:46:47 1991
Endzeit:   Thu Jan 24 08:46:48 1991

Golomb Lineal :
0 1 5 12 25 27 35 41 44 

Zu messende Abst„nde :
  1   2   3   4   5   6   7   8   9  10 
 11  12  13  14  15  16  17  19  20  22 
 23  24  25  26  27  29  30  32  34  35 
 36  39  40  41  43  44 
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 10
Maximale L„nge : 55

Startzeit: Thu Jan 24 08:46:52 1991              59280
Endzeit:   Thu Jan 24 08:46:56 1991    4s        14820/s

Golomb Lineal :
0 1 6 10 23 26 34 41 53 55 

Zu messende Abst„nde :
  1   2   3   4   5   6   7   8   9  10 
 11  12  13  14  15  16  17  18  19  20 
 21  22  23  24  25  26  27  28  29  30 
 31  32  33  34  35  40  41  43  45  47 
 49  52  53  54  55 
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 11
Maximale L„nge : 72

Startzeit: Thu Jan 24 08:47:03 1991              322889
Endzeit:   Thu Jan 24 08:47:16 1991    13s       24838/s

Golomb Lineal :
0 1 4 13 28 33 47 54 64 70 72 

Zu messende Abst„nde :
  1   2   3   4   5   6   7   8   9  10 
 12  13  14  15  16  17  18  19  20  21 
 23  24  25  26  27  28  29  31  32  33 
 34  36  37  39  41  42  43  44  46  47 
 50  51  53  54  57  59  60  63  64  66 
 68  69  70  71  72 
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
Anzahl der Markierungen : 12
Maximale L„nge : 85

Startzeit: Fri Jan 25 10:45:34 1991              71870824
Endzeit:   Fri Jan 25 11:40:39 1991    55m       21779/s

Golomb Lineal :
0 2 6 24 29 40 43 55 68 75 76 85 

Zu messende Abst„nde :
  1   2   3   4   5   6   7   8   9  10 
 11  12  13  14  15  16  17  18  19  20 
 21  22  23  24  25  26  27  28  29  30 
 31  32  33  34  35  36  37  38  39  40 
 41  42  43  44  45  46  47  49  51  52 
 53  55  56  61  62  66  68  69  70  73 
 74  75  76  79  83  85 

ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
